/*
 *
 * Exchange constants
 *
 */

export const DEFAULT_ACTION = 'app/Exchange/DEFAULT_ACTION';
export const REQUEST_ORDER_BOOK = 'REQUEST_ORDER_BOOK';
export const ORDER_BOOK_SUCCESS = 'ORDER_BOOK_SUCCESS';
export const ORDER_BOOK_ERROR = 'ORDER_BOOK_ERROR';
export const REQUEST_BUY_ORDER = 'REQUEST_BUY_ORDER';
export const BUY_ORDER_SUCCESS = 'BUY_ORDER_SUCCESS';
export const BUY_ORDER_ERROR = 'BUY_ORDER_ERROR';
export const REQUEST_SELL_ORDER = 'REQUEST_SELL_ORDER';
export const SELL_ORDER_SUCCESS = 'SELL_ORDER_SUCCESS';
export const SELL_ORDER_ERROR = 'SELL_ORDER_ERROR';

export const REQUEST_CANDLES = 'ORDER_BOOK_ERROR';
export const CANDLES_SUCCESS = 'ORDER_BOOK_ERROR';
export const CANDLES_ERROR = 'ORDER_BOOK_ERROR';
